# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='account',
        ),
    ]
